version: "3.8"

services:
  bgpalerter:
    image: mmartineznetdev/solo-bgpalerter
    command: run serve -- --d /opt/bgpalerter/volume/
    container_name: SOLO-bgpalerter
    volumes:
      - "./volume:/opt/bgpalerter/volume"
    restart: always
